In [9]:
println("I'm stoked to learn Julia!")

I'm stoked to learn Julia!


In [8]:
123
456

456

In [7]:
#semicolon supressed final line std output
123
456;

In [ ]:
#=

for multiline comments, das cool

=#

In [10]:
string = "I am string"
string2 = """ This string can have "quotes" and such """

" This string can have \"quotes\" and such "

In [13]:
#glue like capabilies innately ready

a = 5
b = 6

math_string = "this string can do math $(a+b)!"




"this string can do math 11!"

In [1]:
##concat with string() - it's basically paste() from R?
#string("me ", "and me")

#string function does not seem to work as taught, deprecated?

#can mult to concat, that's super weird but ok
"testing"*"123"

what = "is this "

working = "thing on"


#Can link as well with $, all enclosed in quotes
"$what$working"

"is this thing on"

In [20]:
#Data Structs


#Dictionary

fone_booky = Dict("me" => "513-375-6348", "not me" => "513-555-555");

fone_booky

#add entries with 

fone_booky["new entry"] = "513-999-9999"

fone_booky

#Same synatax for grabbing entries (scan the assignement)
fone_booky["new entry"]


#pop!() functrion returns value AND removed it from dictionary - #that's cool

pop!(fone_booky,"me")

fone_booky

#dicts not ordered, tuples and arrays are


#Tuples

animals = ("dog", "elephant", "octopus")


#arrays mutable and ordered

friends = ["Ed", "Tyler", "Gabe", "Jeff"]

friends[3]

#push() function add to end or array - pop function works here as #well

push!(friends,"Cappa")

friends

rando = rand(5,5,5,5) #TESSARACT





5×5×5×5 Array{Float64,4}:
[:, :, 1, 1] =
 0.308964  0.0821372  0.945254  0.495738  0.111324
 0.770204  0.428504   0.488649  0.956245  0.590555
 0.280791  0.963087   0.978534  0.23601   0.678308
 0.254155  0.790815   0.206166  0.503182  0.928308
 0.421206  0.618976   0.176833  0.807504  0.279361

[:, :, 2, 1] =
 0.764999   0.613228  0.974249  0.218954  0.862646
 0.310546   0.446798  0.235068  0.336164  0.75249
 0.0449033  0.955618  0.741041  0.850954  0.308019
 0.0540213  0.149125  0.306158  0.650636  0.834283
 0.228764   0.313429  0.4673    0.737656  0.931873

[:, :, 3, 1] =
 0.523925  0.946402   0.489218  0.167094   0.0399384
 0.685005  0.153523   0.884058  0.0446771  0.457626
 0.187106  0.268503   0.253128  0.998669   0.1217
 0.542927  0.0288505  0.756045  0.690079   0.993284
 0.66075   0.625861   0.53761   0.568272   0.59727

[:, :, 4, 1] =
 0.448752  0.231262  0.437456  0.836246   0.769486
 0.505991  0.263565  0.998175  0.431825   0.493198
 0.771012  0.6457    0.549312  0.0163604  

In [30]:
#loops!

#=

for *var* in *loop iter*
    *loop body*
end
=#


for friend in friends
  println("Yo $friend sup dawg")
end


#∈ works as well, uhh how do I type this?

#mult assignment on same line, neato
m,n = 5,5

A = zeros(m,n)

for i in 1:m
  for j in 1:n
    A[i,j] = i + j
  end
end

#A

###condensed form

B = zeros(m,n)

#basically can collapse nested loops, very cool!
for i in 1:m, j in 1:n
  B[i,j] = i + j
end

B

#"Julian" Way would be an array-comprehension
#no end statement, no pre-initialize table
C = [i + j for i in 1:m, j in 1:n]


##growing tables
## loop with array comp


for n in 1:8
    A = [i + j for i in 1:n, j in 1:n]
  display(A)
end



1×1 Array{Int64,2}:
 2

2×2 Array{Int64,2}:
 2  3
 3  4

3×3 Array{Int64,2}:
 2  3  4
 3  4  5
 4  5  6

4×4 Array{Int64,2}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

6×6 Array{Int64,2}:
 2  3  4   5   6   7
 3  4  5   6   7   8
 4  5  6   7   8   9
 5  6  7   8   9  10
 6  7  8   9  10  11
 7  8  9  10  11  12

7×7 Array{Int64,2}:
 2  3   4   5   6   7   8
 3  4   5   6   7   8   9
 4  5   6   7   8   9  10
 5  6   7   8   9  10  11
 6  7   8   9  10  11  12
 7  8   9  10  11  12  13
 8  9  10  11  12  13  14

8×8 Array{Int64,2}:
 2   3   4   5   6   7   8   9
 3   4   5   6   7   8   9  10
 4   5   6   7   8   9  10  11
 5   6   7   8   9  10  11  12
 6   7   8   9  10  11  12  13
 7   8   9  10  11  12  13  14
 8   9  10  11  12  13  14  15
 9  10  11  12  13  14  15  16

Yo Ed sup dawg
Yo Tyler sup dawg
Yo Gabe sup dawg
Yo Jeff sup dawg
Yo Cappa sup dawg
